project:
  type: website
  output-dir: docs

website:
  title: "Ting-Hsuan Chang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

